import { Category } from '@/types/database';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Food', icon: 'restaurant', color: '#FF6B6B' },
  { id: '2', name: 'Transport', icon: 'car', color: '#4ECDC4' },
  { id: '3', name: 'Shopping', icon: 'cart', color: '#45B7D1' },
  { id: '4', name: 'Entertainment', icon: 'game-controller', color: '#F7B731' },
  { id: '5', name: 'Bills', icon: 'receipt', color: '#5F27CD' },
  { id: '6', name: 'Health', icon: 'medical', color: '#00D2D3' },
  { id: '7', name: 'Education', icon: 'school', color: '#FEA47F' },
  { id: '8', name: 'Travel', icon: 'airplane', color: '#1DD1A1' },
  { id: '9', name: 'Home', icon: 'home', color: '#FF9FF3' },
  { id: '10', name: 'Gifts', icon: 'gift', color: '#F368E0' },
  { id: '11', name: 'Sports', icon: 'football', color: '#48DBFB' },
  { id: '12', name: 'Other', icon: 'ellipsis-horizontal', color: '#A3A3A3' },
  { id: '13', name: 'Groceries', icon: 'basket', color: '#26DE81' },
  { id: '14', name: 'Coffee', icon: 'cafe', color: '#6F4E37' },
  { id: '15', name: 'Fitness', icon: 'barbell', color: '#FC5C65' },
  { id: '16', name: 'Gas', icon: 'speedometer', color: '#FD9644' },
  { id: '17', name: 'Pet Care', icon: 'paw', color: '#A55EEA' },
  { id: '18', name: 'Books', icon: 'book', color: '#8854D0' },
  { id: '19', name: 'Music', icon: 'musical-notes', color: '#F97F51' },
  { id: '20', name: 'Movies', icon: 'film', color: '#3867D6' },
  { id: '21', name: 'Clothing', icon: 'shirt', color: '#FA8231' },
  { id: '22', name: 'Beauty', icon: 'cut', color: '#EE5A6F' },
  { id: '23', name: 'Electronics', icon: 'phone-portrait', color: '#778BEB' },
  { id: '24', name: 'Furniture', icon: 'bed', color: '#786FA6' },
  { id: '25', name: 'Garden', icon: 'leaf', color: '#2ECC71' },
  { id: '26', name: 'Repairs', icon: 'construct', color: '#F8B500' },
  { id: '27', name: 'Insurance', icon: 'shield-checkmark', color: '#546DE5' },
  { id: '28', name: 'Savings', icon: 'wallet', color: '#20BF6B' },
  { id: '29', name: 'Dining Out', icon: 'pizza', color: '#FF793F' },
  { id: '30', name: 'Subscriptions', icon: 'repeat', color: '#C44569' },
  { id: '31', name: 'Kids', icon: 'people', color: '#F8C291' },
  { id: '32', name: 'Charity', icon: 'heart', color: '#E74C3C' },
];
